name: '.NET Core Publish'
author: 'Tom McKinney, UpstreamCode'
description: 'Simple action for building .NET Core packages and pushing them to NuGet'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  project-path:
    description: 'Path to project'
    required: true

outputs:
  result:
    description: 'Result of the tests'

runs:
  using: 'node12'
  main: 'dist/index.js'
